apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common-service.fullname" . }}
  labels:
    app: {{ include "common-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "common-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "common-service.name" . }}
    spec:
      containers:
        - name: {{ include "common-service.name" . }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}